version: '3'

services:
  web:
      build: .
      container_name: blog_indrian
      command: gunicorn mysite.wsgi.application --bind 0.0.0.0:9001

      volumes:
          - .:/app
      ports:
          - "9001:9001"